### PR TITLE
Update code to swf-tree 0.0.14 and replace some dependencies with pure-Rust versions.

### PR DESCRIPTION
**Pull request by eddyb**
Not needing C dependencies makes the code more portable (I couldn't even find the C library that `rust-lzma` needs), and would likely make it easier to compile to WASM.

### CODE REVIEW

**Comment by demurgos** [comment]
Hi, thanks for the PR. I missed it in the last months: I'll take a look at it.

**Comment by eddyb** [comment]
@demurgos Hey! I'm not currently working on [`flashback`](https://github.com/lykenware/flashback) but you might want to take a look at the changes I made in https://github.com/lykenware/swf-parser/commit/ab64b540942bada6a60cd76466eb743d3f845206 - it resulted in a lot more files parsing for me.

Sadly, not everything, see http://cdn.mspaintadventures.com/storyfiles/hs2/02791/02791.swf and http://zombo.com/inrozxa.swf for two examples that still don't, IIRC.

**Comment by demurgos** [comment]
Hi,
I had some time to merge your updates. Since you commited on `master` I couldn't rebased your branch so I cherry picked your commits adding pure Rust versions.

I had some time to look at Flashback: it looks really great. As you noted in your README, we have similar goals. My roadmap is to have a baseline TS player, then a perf-focused Rust player. Longer term I wanted to have a converter like yours. I can now play simple animations with the [Domu player](https://github.com/open-flash/domu-player), this was a milestone for me. I'll now pay more attention to have a more reliable project, a proper changelog, CI, regression tests, documentation, etc. I'll take a look at the SWF files that you can't parse.

**Comment by demurgos** [comment]
The current `master` can parse both of the files you linked without panicking but there are a few tags that are left as `unknown` (not implemented). I'll implement them and publish the new version.

**Comment by eddyb** [comment]
@demurgos Looking back at my list of commits, I'm seeing you didn't remove the redundant `^` from `Cargo.toml` versions, is that intentional?
(`^` is the default so you never have to add it explicitly)

**Comment by eddyb** [comment]
@demurgos You probably want some separate reports for these (let me know), but this file now fails to parse: http://cdn.mspaintadventures.com/storyfiles/hs2/02577/02577.swf - by panicking here https://github.com/open-flash/swf-parser/blob/2dadb1f38e3da290e31a540ed32c7927a7dcb74e/rs/src/parsers/button.rs#L114.

But, here's something for your troubles: [the zombo.com SWF that used to not parse](https://jsfiddle.net/eddyb/26r8bs30/show/) :tada:.

**Comment by demurgos** [comment]
Regarding the dependencies I prefer to keep the explicit semver range (`^`) for consistency between `npm` and `crates` (they have different defaults). These kinds of inconsistencies are some of the reasons for the creation of the [new semver team](https://words.steveklabnik.com/what-s-next-for-semver): they can be an obstacle between various ecosystems.

The keycode error may be caused by the keycode 8: I noticed that it is valid according to the spec but the parser does not accept it. If it's not the keycode 8, it means that the spec does not match real-world usage.

I started to centralize SWF samples in the repo [open-flash-db/standalone-movies](https://github.com/open-flash-db/standalone-movies). For the moment I am collecting SWF files that can be played without loading other files / requiring the browser, special parameters, etc. These files are then used for the `swf-tree` and `swf-parser` tests. If you have some files, sending them there would ensure that any regression is caught automatically now that CI is enabled.

**Comment by eddyb** [comment]
> Regarding the dependencies I prefer to keep the explicit semver range (`^`) for consistency between `npm` and `crates` (they have different defaults). These kinds of inconsistencies are some of the reasons for the creation of the [new semver team](https://words.steveklabnik.com/what-s-next-for-semver): they can be an obstacle between various ecosystems.

Ah, I meant to ask if there is a reason like that for it! Can you add a comment to wherever you do this, that there is a purpose to it and all dependency modifications should keep `^`?
`cargo add`, for example, doesn't by default.

> The keycode error may be caused by the keycode 8: I noticed that it is valid according to the spec but the parser does not accept it. If it's not the keycode 8, it means that the spec does not match real-world usage.

I was too tired to check, but if you change the panic to show the key code and run the file through the parser, you'd have your answer. Maybe this is about inclusive vs exclusive ranges?

> I started to centralize SWF samples in the repo [open-flash-db/standalone-movies](https://github.com/open-flash-db/standalone-movies). For the moment I am collecting SWF files that can be played without loading other files / requiring the browser, special parameters, etc. These files are then used for the `swf-tree` and `swf-parser` tests. If you have some files, sending them there would ensure that any regression is caught automatically now that CI is enabled.

I don't know about copyright issues, everything I use for testing is off the internet.
Homestuck and z0r.de were recommended by @whitequark, IIRC, and I locally have a dozen SWFs from both that I kept trying to get working as much as possible, plus another dozen from some random website that has Flash animation examples for download.

**Comment by demurgos** [comment]
> Ah, I meant to ask if there is a reason like that for it! Can you add a comment to wherever you do this, that there is a purpose to it and all dependency modifications should keep ^?
cargo add, for example, doesn't by default.

Okay, I'll add a comment for the caret. When adding/updating dependencies it would be nice to keep it. If it turns out that fighting against the existing tools (`cargo add` etc) is too much work, I am okay with simply removing it.

---

> I was too tired to check, but if you change the panic to show the key code and run the file through the parser, you'd have your answer. Maybe this is about inclusive vs exclusive ranges?

Agreed: the error should provide more information. Ideally we'd never panick and return a proper error but I haven't looked into custom errors yet.

---

Regarding test samples, I also just use some files off the internet. I also have some files locally but I am working into building a collection of real-world files to test against. Shumway had such a database, I remember finding the link some day and connecting to it via Github (I should try to retrieve it).
Regarding copyright issues I am not expert but I feel that as long as the files are freely accessible on the internet it should be fine, the goal isn't even to host/share content just to help with testing.

**Comment by eddyb** [comment]
I must've not retried all the files: http://cdn.mspaintadventures.com/storyfiles/hs2/00031/00031.swf is now failing with `Incomplete(Unknown)`.

Let me know where I should open better bug reports! Maybe make an issue with everything I hit while testing `flashback`?

**Comment by demurgos** [comment]
@eddyb I found the issue, it was related to how button2 actions were handled. Previously, AVM1 actions were parsed eagerly. This caused some issues because there wasn't enough information so now AVM1 actions are left as bytes. The problem with button2 actions was related to a bug with the way AVM1 offsets were computed in the presence of multiple transitions. I'll publish a patch soon.

To prevent regressions in the future, submit your files [to this repo](https://github.com/open-flash-db/standalone-movies). These files are used in CI so once they're in the repo, they won't break.

**Comment by eddyb** [comment]
> To prevent regressions in the future, submit your files to this repo. These files are used in CI so once they're in the repo, they won't break.

Sorry, but I don't own these, and I'm not sure you should be hosting a copy of them, but I'm not a lawyer.

**Comment by demurgos** [comment]
Ok, thanks for the clarification.
I still feel that it should be fine to have this kind of mirror but I am not an expert either.

An idea would be to only keep the file URLs and provide a tool to download the files from the original URL instead of keeping the files in a repo.

**Comment by demurgos** [comment]
@eddyb Ok, I'll remove the SWF that I did not author then.

**Pull request closed without merging**
